---
twitter: https://twitter.com/TatsuroYamshita
github: https://github.com/BrianXS/
linkedin: ''
youtube: https://www.youtube.com/channel/UCjJ5_lGSoZfEarYpvjMmVuw
dribbble: ''
instagram: https://www.instagram.com/tatsuro_yamashita/
facebook: ''
medium: ''
patreon: ''
paypal: ''
unsplash: ''
